<?php
/**
 * @file
 * Code for the CRF Workbench feature.
 */

include_once 'crf_workbench.features.inc';

/**
 * Implements hook_menu_alter().
 */
function crf_workbench_menu_alter(&$items) {
  // Override the node edit menu item title.
  $items['node/%node/edit']['title callback'] = 'crf_workbench_edit_tab_title';
  $items['node/%node/edit']['title arguments'] = array(1);
}


/**
 * Implements hook_workbench_access_node_element_alter().
 */
function crf_workbench_workbench_access_node_element_alter(&$element, $form_state, $active) {
  // Hide section select box. If the current user has permission to
  // edit the form we can savely assume the node belongs to a section
  // his or her role belongs to.
  global $user;
  if (isset($element)) {
    $element['#type'] = 'hidden';
    
    $ocha_term = taxonomy_get_term_by_name('OCHA', 'sections');
    $clusters_term = taxonomy_get_term_by_name('Clusters', 'sections');
    
    if (in_array('manager', $user->roles)) {
      $element['#value'] = array(current(array_keys($ocha_term)));
    }
    else if (in_array('editor', $user->roles)) {
      $element['#value'] = array(current(array_keys($clusters_term)));
    }
  }
}

// Lifted from workbench_moderation_edit_tab_title()
function crf_workbench_edit_tab_title($node) {
  if (isset($node->workbench_moderation)) {
    $state = $node->workbench_moderation;

    // Use the normal tab title if the node type is not under moderation
    // or if it's published (ie finalised).
    if (!workbench_moderation_node_type_moderated($node->type) ||
       (!empty($state['published']) && $state['published']->vid == $state['current']->vid)) {
      return t('Edit');
    }
  }

  // The latest draft is not published.
  return t('Edit draft');
}
